Repository lnykryn/systemd-rhel, pull requests merged in 2018-07, with the labels that each got.

#223 rules: mark hotplugged memory as movable (#1563532)
  rules/40-redhat.rules
Labels: merge-ready, rhel-7.6

#224 udev: add ID_INPUT_SWITCH for devices with switch capability (#1597240)
  src/udev/udev-builtin-input_id.c
Labels: merge-ready, rhel-7.6

#222 rules: disable support for Dell IR cameras (#1591316)
  Makefile.am
  rules/40-redhat-disable-dell-ir-camera.rules
Labels: ci-waive, merge-ready, rhel-7.6

#220 (#1582383) rpm: fix %systemd_user_post() macro.
  src/core/macros.systemd.in
Labels: ci-waive, merge-ready

#219 (#1596241) automount: handle state changes of the corresponding mount unit corre…
  src/core/automount.c
Labels: ci-waive, merge-ready, rhel-7.6

#221 (#1601794) man: document that SIGCONT always follows SIGTERM
  man/systemd.kill.xml
Labels: ci-waive, merge-ready, sanity-only

#225 rules: add udev rule that automatically offline HW attached to ACPI container (#1597958)
  Makefile.am
  rules/40-redhat-hotunplug.rules
Labels: ci-waive, merge-ready, rhel-7.6
