Repository lnykryn/systemd-rhel, pull requests merged in 2018-06, with the labels that each got.

#201 tmpfiles: don't skip cleanup of read-only root owned files if TMPFILES_AGE_ALL is set (#1533638)
  src/tmpfiles/tmpfiles.c
Labels: has-test, merge-ready, rhel-7.6

#198 (#1549119) timer: we already got the trigger before, no need to call UNIT_TRIGGE…
  src/core/timer.c
Labels: ci-waive, merge-ready, rhel-7.6, sanity-only

#203 (#1572244) doc: fix links to binfmt_misc kernel documentation
  man/binfmt.d.xml
  src/test/test-util.c
  units/proc-sys-fs-binfmt_misc.automount
  units/proc-sys-fs-binfmt_misc.mount
  units/systemd-binfmt.service.in
Labels: ci-waive, merge-ready, rhel-7.6, sanity-only

#200 (#1553076) man/udevadm: remove superfluous --version from subcommand
  man/udevadm.xml
Labels: ci-waive, merge-ready, rhel-7.6, sanity-only

#199 (#1552712) man/udevadm: correctly show the short version of --exit
  man/udevadm.xml
Labels: ci-waive, merge-ready, rhel-7.6, sanity-only

#210 (#1587906) core/timer: downgrade message about random time addition
  src/core/timer.c
Labels: merge-ready, needs-test

#204 (#1573838) cryptsetup: support LUKS2 on-disk format
  src/cryptsetup/cryptsetup.c
Labels: ci-waive, has-test, merge-ready, rhel-7.6

#186 core:scope: fix missing fragment_path (#1550534)
  src/core/load-fragment.c
  src/core/scope.c
Labels: ci-waive, has-test, merge-ready, rhel-7.6

#185 units: don't put udev to its own mount namespace with slave propagation (#1432211)
  units/systemd-udevd.service.in
Labels: ci-waive, has-test, merge-ready, rhel-7.6

#211 rules: disable support for Lenovo IR cameras (#1540418)
  Makefile.am
  rules/40-redhat-disable-lenovo-ir-camera.rules
Labels: ci-waive, merge-ready, rhel-7.6, sanity-only

#209 (#1191920) core: make sure "systemctl reload-or-try-restart is actually a noop i…
  src/core/dbus-unit.c
  src/core/job.c
  src/core/job.h
  src/core/unit.c
Labels: ci-waive, has-test, merge-ready

#193 mount: add new LazyUnmount= setting for mount units, mapping to umount(8)'s "-l" switch (#1497264)
  man/systemd.mount.xml
  src/core/dbus-mount.c
  src/core/load-fragment-gperf.gperf.m4
  src/core/mount.c
  src/core/mount.h
Labels: ci-waive, has-test, merge-ready, rhel-7.6

#217 rules: Add MODEL_ID for NVMe device (#1397264)
  rules/60-persistent-storage.rules
Labels: merge-ready, rhel-7.6

#213 (#1247963) journal: fix HMAC calculation when appending a data object
  src/journal/journal-file.c
Labels: merge-ready, rhel-7.6

#212 journal: forward messages from /dev/log unmodified to syslog.socket (#1409659)
  src/journal/journald-server.c
  src/journal/journald-syslog.c
  src/journal/journald-syslog.h
Labels: merge-ready

#208 (#1436004) tmpfiles: use safe_glob()
  src/shared/util.c
  src/shared/util.h
  src/tmpfiles/tmpfiles.c
Labels: merge-ready, needs-test

#207 (#1316278) fix SELinux labels in cgroup filesystem root directory
  src/core/mount-setup.c
Labels: merge-ready, needs-test, rhel-7.6

#206 (#1351793) fix race between daemon-reload and other commands
  src/core/job.c
  src/core/job.h
  src/core/manager.c
  src/core/manager.h
Labels: merge-ready, needs-test, rhel-7.6

#214 core: delay adding target dependencies until all units are loaded and aliases resolved (#1368856)
  src/core/manager.c
  src/core/manager.h
  src/core/unit.c
  src/core/unit.h
Labels: merge-ready

#218 (#1305509) man: correct the meaning of TimeoutStopSec=
  man/systemd.service.xml
Labels: ci-waive, merge-ready
