Repository lnykryn/systemd-rhel, pull requests merged in 2018-12, with the labels that each got.

#248 dhcp6: make sure we have enough space for the DHCP6 option header (#1643363)
  src/libsystemd-network/dhcp6-option.c
Labels: merge-ready, rhel-8.0, rhel-next

#240 Revert "sysctl.d: request ECN on both in and outgoing connections" (#1619790)
  sysctl.d/50-default.conf
Labels: ci-waive, merge-ready, rhel-8.0, rhel8

#239 detect-virt: do not try to read all of /proc/cpuinfo (#1631532)
  src/basic/virt.c
Labels: ci-waive, merge-ready, rhel-8.0, rhel8

#255 (#1653824) sysctl.d: switch net.ipv4.conf.all.rp_filter from 1 to 2
  sysctl.d/50-default.conf
Labels: ci-waive, merge-ready, rhel8
