Repository lnykryn/systemd-rhel, pull requests merged in 2019-02, with the labels that each got.

#286 (#1626382) core: disable the effect of Restart= if there's a stop job pending fo…
  src/core/service.c
Labels: merge-ready, rhel7

#270 (#1663365) networkd: respect DHCP UseRoutes option
  src/network/networkd-dhcp4.c
Labels: merge-ready, rhel7

#292 (#1653824) Revert "sysctl.d: switch net.ipv4.conf.all.rp_filter from 1 to 2"
  sysctl.d/50-default.conf
Labels: merge-ready, rhel8

#253 (#1641764) tmpfiles 'e' glob backports
  src/tmpfiles/tmpfiles.c
Labels: merge-ready, rhel7

#249 bus-message: do not crash on message with a string of zero length (#1643396)
  src/libsystemd/sd-bus/bus-message.c
  test/fuzz/fuzz-bus-message/crash-29ed3c202e0ffade3cad42c8bbeb6cc68a21eb8e
Labels: merge-ready, rhel7

#243 (#1651257) set automount state to waiting when the mount is stopped
  src/core/automount.c
Labels: merge-ready, rhel7

#232 (#1631625) shorten hostname before checking for trailing dot
  src/shared/util.c
Labels: merge-ready, rhel7

#230 (#1619543) journald: fixed assertion failure when system journal rotation fails
  src/journal/journald-server.c
Labels: merge-ready, rhel7

#291 (#1627750) local-addresses: handle gracefully if routes lack an RTA_OIF attribute
  src/libsystemd/sd-rtnl/local-addresses.c
Labels: merge-ready, rhel7

#285 (#1664978) (CVE-2018-16866) journal: fix syslog_parse_identifier()
  src/journal/journald-syslog.c
  src/journal/test-journal-syslog.c
Labels: merge-ready, rhel8

#280 (#1666612) rules: fix memory hotplug rule so systemd-detect-virt does not run too often
  rules/40-redhat.rules
Labels: merge-ready, rhel7

#273 (#1658115) journald: correctly attribute log messages also with cgroupsv1
  src/journal/journald-context.c
Labels: merge-ready, rhel8

#262 (#1664695) use path_startswith("/dev") in cryptsetup (#6732)
  src/cryptsetup/cryptsetup-generator.c
Labels: merge-ready, rhel7

#260 (#1585411) core: mount-setup: handle non-existing mountpoints gracefully
  src/core/mount-setup.c
Labels: merge-ready, rhel7

#257 (#1660422) units/rescue.service.in: fix announcement message
  units/rescue.service.in
Labels: merge-ready, rhel7

#254 (#1649518) systemctl: Allow 'edit' and 'cat' on unloaded units
  src/systemctl/systemctl.c
Labels: merge-ready, rhel7

#297 test: replace echo with socat
  test/TEST-10-ISSUE-2467/test.sh
Labels: needs-review, rhel8

#288 test-network: ignore tunnel devices automatically added by kernel
  test/test-execute/exec-privatenetwork-yes.service
Labels: merge-ready, rhel8

#290 (#1585913) main: improve RLIMIT_NOFILE handling (#5795)
  src/core/main.c
Labels: merge-ready, rhel7

#279 (#1609816) shared/sleep-config: exclude zram devices from hibernation candidates
  src/shared/sleep-config.c
Labels: merge-ready, rhel7

#278 (#1463678) journalctl: allow --file/--directory with --boot or --list-boots
  src/journal/journalctl.c
Labels: merge-ready, rhel7

#277 (#1267552) journal-remote: show error message if output file name does not end w…
  src/journal-remote/journal-remote.c
Labels: merge-ready, rhel7

#296 (#1670126) rules: add elevator= kernel command line parameter
  rules/40-elevator.rules
Labels: merge-ready, rhel8

#282 (#1272485) artificially serialize building of .policy files
  Makefile.am
Labels: merge-ready, reviewed/needs-rework, rhel7

#299 tests: run `udevadm settle` after `fdisk`
  test/test-functions
Labels: needs-review, rhel7, test-only

#298 rule-syntax-check: allow PROGRAM as an assignment
  test/rule-syntax-check.py
Labels: needs-review, rhel8, test-only

#281 (#1670728) rules: implement new memory hotplug policy
  rules/40-redhat.rules
Labels: merge-ready, rhel8

#295 (#1657794) (CVE-2018-16866) journal: fix syslog_parse_identifier()
  src/journal/journald-syslog.c
  src/journal/test-journal-syslog.c
Labels: merge-ready, rhel7

#310 (#1670126) rules: add the rule that adds elevator= kernel command line parameter
  rules/meson.build
Labels: merge-ready, rhel8
