Repository lnykryn/systemd-rhel, pull requests merged in 2019-01, with the labels that each got.

#265 test: Drop SKIP_INITRD for QEMU-based tests
  test/TEST-08-ISSUE-2730/test.sh
  test/TEST-09-ISSUE-2691/test.sh
  test/TEST-10-ISSUE-2467/test.sh
  test/TEST-11-ISSUE-3166/test.sh
  test/TEST-13-NSPAWN-SMOKE/test.sh
  test/TEST-14-MACHINE-ID/test.sh
Labels: merge-ready, rhel8

#258 (#1619292) unit: don't add Requires for tmp.mount
  src/core/unit.c
Labels: merge-ready, rhel8

#269 tests: drop the precondition check for inherited flag
  src/test/test-capability.c
Labels: needs-review, rhel8

#271 (#1666646) journald: free cmdline buffers owned by iovec
  src/journal/journald-server.c
Labels: merge-ready, rhel7

#264 test: 01-basic: mask some services that currently don't run in qemu
  test/TEST-01-BASIC/test.sh
Labels: merge-ready, rhel7

#233 (#1631531) detect-virt: do not try to read all of /proc/cpuinfo
  src/shared/virt.c
Labels: merge-ready, rhel7
