Repository lnykryn/systemd-rhel, pull requests merged in 2019-03, with the labels that each got.

#303 test: add TEST-24-UNIT-TESTS running all basic tests under containers
  test/TEST-24-UNIT-TESTS/Makefile
  test/TEST-24-UNIT-TESTS/test.sh
  test/TEST-24-UNIT-TESTS/testsuite.sh
Labels: needs-review, rhel8, test-only

#242 (#1628575) Backport shared/install: allow "enable" on linked unit files
  src/shared/install.c
  src/test/test-install-root.c
Labels: ci-waive, merge-ready, rhel7

#315 `test/test-functions` backports
  test/TEST-01-BASIC/test.sh
  test/test-functions
Labels: needs-review, rhel8, test-only

#316 test: don't overwrite TESTDIR if already set
  test/test-functions
Labels: needs-review, rhel8, test-only

#319 (#1692991) bus-socket: Fix line_begins() to accept word matching full string
  src/libsystemd/sd-bus/bus-socket.c
Labels: merge-ready, rhel8

#235 (#1361893) journald: respect KeepFree= as well as MaxUse= values
  src/journal/journald-server.c
Labels: merge-ready, rhel7

#321 (#1693716) shutdown: in_container was used before its definition
  src/core/shutdown.c
Labels: merge-ready, rhel7
