Repository lnykryn/systemd-rhel, pull requests merged in 2019-05, with the labels that each got.

#331 (#1697909) Fix hangs in spawn_wait()
  src/udev/udev-event.c
Labels: merge-ready, rhel7

#333 (#1697909) avoid possible hang if our child process hangs
  src/udev/udev-event.c
Labels: merge-ready, rhel7

#323 (#1695601) logs-show: use grey color for de-emphasizing journal log output
  src/basic/terminal-util.h
  src/shared/logs-show.c
Labels: merge-ready, rhel8

#275 (#1667065) enable tmp mount
  units/tmp.mount
Labels: merge-ready, rhel8

#294 (#1643394) sd-bus: unify three code-paths which free struct bus_container
  src/libsystemd/sd-bus/bus-message.c
Labels: ci-waive, merge-ready, rhel7

#256 seccomp: reduce logging about failure to add syscall to seccomp (#1658691)
  src/core/execute.c
  src/nspawn/nspawn-seccomp.c
  src/shared/seccomp-util.c
  src/shared/seccomp-util.h
  src/test/test-seccomp.c
Labels: ci-waive, merge-ready, rhel8
